I'm sorry, but an uncaught exception occurred.

While running game code:
  File "definitions.rpy", line 153, in <module>
NameError: name 'italianBeep' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Applications/Ren'Py/renpy/bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "/Applications/Ren'Py/renpy/main.py", line 526, in main
    renpy.game.context().run(node)
  File "game/definitions.rpyc", line 153, in script
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "game/definitions.rpyc", line 153, in script
  File "/Applications/Ren'Py/renpy/ast.py", line 2222, in execute
    self.set()
  File "/Applications/Ren'Py/renpy/ast.py", line 2236, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "/Applications/Ren'Py/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "definitions.rpy", line 153, in <module>
NameError: name 'italianBeep' is not defined

macOS-14.5-arm64-arm-64bit arm64
Ren'Py 8.2.3.24061702
Office Simulator 2025 InfDev
Mon Aug  5 22:44:26 2024
