I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/rooms/elevator.rpy", line 44, in script
    $ moveElevator(2)
  File "game/scripts/rooms/elevator.rpy", line 44, in <module>
    $ moveElevator(2)
  File "game/scripts/rooms/elevator.rpy", line 25, in moveElevator
    with_statement(Shake((0, 0, 0, 0), 2.875, dist=5), True)
TypeError: '_Feature' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/rooms/elevator.rpy", line 44, in script
    $ moveElevator(2)
  File "/Applications/Ren'Py/renpy/ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Applications/Ren'Py/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/scripts/rooms/elevator.rpy", line 44, in <module>
    $ moveElevator(2)
  File "game/scripts/rooms/elevator.rpy", line 25, in moveElevator
    with_statement(Shake((0, 0, 0, 0), 2.875, dist=5), True)
TypeError: '_Feature' object is not callable

macOS-14.5-arm64-arm-64bit arm64
Ren'Py 8.2.3.24061702
Office Simulator 2025 InfDev
Sat Aug  3 16:26:55 2024
