I'm sorry, but an uncaught exception occurred.

While running game code:
Exception: Sayer 'n' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/rooms/hallway/hallway_vendingMachine.rpyc", line 11, in script
  File "/Applications/Ren'Py/renpy/ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Applications/Ren'Py/renpy/ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'n' is not defined.

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.0.3.22090809
Office Simulator 2025 Dev Version
Thu Apr  4 11:43:52 2024
